# -*- coding: utf-8 -*-
"""Agente de Avaliação de Imóveis com Google API

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Us9zhYDkJjVjYnYByPRGx_APy5PEpgYR
"""

# Commented out IPython magic to ensure Python compatibility.
%pip -q install google-genai

# Configura a API Key do Google Gemini

import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')

# Configura o cliente da SDK do Gemini

from google import genai

client = genai.Client()

MODEL_ID = "gemini-2.0-flash"

# Commented out IPython magic to ensure Python compatibility.
# Instalar Framework ADK de agentes do Google ################################################
%pip install -q google-adk

from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.tools import google_search
from google.genai import types  # Para criar conteúdos (Content e Part)
from datetime import date
import textwrap # Para formatar melhor a saída de texto
from IPython.display import display, Markdown # Para exibir texto formatado no Colab
import requests # Para fazer requisições HTTP
import warnings

warnings.filterwarnings("ignore")

# Função auxiliar que envia uma mensagem para um agente via Runner e retorna a resposta final
def call_agent(agent: Agent, message_text: str) -> str:
    # Cria um serviço de sessão em memória
    session_service = InMemorySessionService()
    # Cria uma nova sessão (você pode personalizar os IDs conforme necessário)
    session = session_service.create_session(app_name=agent.name, user_id="user1", session_id="session1")
    # Cria um Runner para o agente
    runner = Runner(agent=agent, app_name=agent.name, session_service=session_service)
    # Cria o conteúdo da mensagem de entrada
    content = types.Content(role="user", parts=[types.Part(text=message_text)])

    final_response = ""
    # Itera assincronamente pelos eventos retornados durante a execução do agente
    for event in runner.run(user_id="user1", session_id="session1", new_message=content):
        if event.is_final_response():
          for part in event.content.parts:
            if part.text is not None:
              final_response += part.text
              final_response += "\n"
    return final_response

# Função auxiliar para exibir texto formatado em Markdown no Colab
def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

##########################################
# --- Agente 1: Buscador de Laudos Periciais --- #
##########################################
def agente_buscador(topico, data_de_hoje):
    buscador = Agent(
        name="agente_buscador",
        model="gemini-2.0-flash",
        instruction="""
        Você é um Assistente de Pesquisa Técnica e Desenvolvedor de Laudos Periciais na área de Engenharia Civil.
        Sua tarefa é utilizar mecanismos de busca (como o Google Search) para localizar decisões recentes do Tribunal de Justiça que envolvam laudos periciais aprovados ou rejeitados relacionados ao tema indicado.
        Priorize até 5 exemplos relevantes de cada tipo (laudos aceitos e laudos rejeitados), com base na quantidade e qualidade das informações disponíveis sobre cada caso.
        Desconsidere laudos com pouca repercussão ou escassa fundamentação técnica/jurídica publicada, mesmo que tenham sido mencionados em alguma decisão. Substitua-os por casos com maior documentação pública.
        As decisões e laudos analisados devem ser atuais, com data de emissão ou julgamento de no máximo 5 anos.
        A finalidade é identificar padrões técnicos, erros recorrentes e boas práticas que contribuam para a elaboração de laudos mais robustos e alinhados com as exigências dos Tribunais.
        """,
        description="Agente que busca informações no Google",
        tools=[google_search]
    )

    entrada_do_agente_buscador = f"Tópico: {topico}\nData de hoje: {data_de_hoje}"
    lancamentos = call_agent(buscador, entrada_do_agente_buscador)
    return lancamentos

################################################
# --- Agente 2: Planejador de Laudos Periciais --- #
################################################
def agente_planejador(topico, lancamentos_buscados):
    planejador = Agent(
        name="agente_planejador",
        model="gemini-2.0-flash",
        # Inserir as instruções do Agente Planejador #################################################
        instruction="""
        Você é um planejador de laudos periciais, um perito especialista em periciais e normas relacionadas. Com base na lista de laudos mais recentes e relevantes buscador, você deve:
        usar a ferramenta de busca do Google (google_search) para criar um plano elaborado para o laudo.
        Você também pode usar o (google_search) para encontrar mais informações sobre o tema e aprofundar.
        Diga quem pediu o laudo (o juiz ou a parte interessada) e por que ele está sendo feito.
        Descreva o imóvel (tamanho do lote, área construída se assim possuir, o que tem lá, se tiver uma construção como está o estado da construção).
        Use um método técnico (como por exemplo o comparativo ou evolutivo) para calcular quanto o imóvel vale.
        Ao final, você irá escolher qual forma mais relevante de se fazer o laudo, com base nas suas pesquisas
        e retornar com o resultado, tendo seus pontos mais relevantes e um plano com os assuntos a serem investigados.
        """,
        description="Agente que planeja pericia",
        tools=[google_search]
    )

    entrada_do_agente_planejador = f"Tópico:{topico}\nLançamentos buscados: {lancamentos_buscados}"
    # Executa o agente
    plano_do_laudo = call_agent(planejador, entrada_do_agente_planejador)
    return plano_do_laudo

######################################
# --- Agente 3: Redator do Laudo --- #
######################################
def agente_redator(topico, plano_de_pericia):
    redator = Agent(
        name="agente_redator",
        model="gemini-2.0-flash",
        instruction="""
            Você é um Perito Avaliador especialista em engenharia civil e avaliações técnicas.
            Sua função é elaborar pareceres periciais, avaliações imobiliárias e laudos técnicos fundamentados em normas técnicas e legislação vigente.
            Utilize o tema fornecido no plano de pericia e os pontos técnicos mais relevantes para construir um rascunho de relatório ou laudo claro, preciso e fundamentado.
            O conteúdo deve ser técnico, objetivo e embasado, evitando linguagem excessivamente complexa, mas preservando rigor científico e normativo.
            """,
        description="Agente redator de laudos periciais"
    )
    entrada_do_agente_redator = f"Tópico: {topico}\nPlano de pericia: {plano_de_pericia}"
    # Executa o agente
    rascunho = call_agent(redator, entrada_do_agente_redator)
    return rascunho

##########################################
# --- Agente 4: Revisor de Qualidade --- #
##########################################
def agente_revisor(topico, rascunho_gerado):
    revisor = Agent(
        name="agente_revisor",
        model="gemini-2.0-flash",
        instruction="""
            Você é um Editor e Revisor Técnico meticuloso, especializado em documentos e laudos periciais na área de engenharia civil.
            Considere o público técnico e jurídico ao revisar, garantindo clareza, precisão, concisão e adequação ao padrão normativo e legal vigente.
            Revise o rascunho do laudo ou parecer abaixo sobre o tema indicado, verificando coerência técnica, correção terminológica, clareza e formalidade.
            Caso o documento esteja adequado, responda apenas: “O laudo está tecnicamente consistente e pronto para emissão.”
            Se houver inconsistências ou pontos a melhorar, identifique-os e sugira correções técnicas e formais.
            """,
        description="Agente revisor de laudos periciais."
    )
    entrada_do_agente_revisor = f"Tópico: {topico}\nRascunho: {rascunho_gerado}"
    # Executa o agente
    texto_revisado = call_agent(revisor, entrada_do_agente_revisor)
    return texto_revisado

data_de_hoje = date.today().strftime("%d/%m/%Y")

print("🚀 Iniciando o Sistema de Criação de Laudos Periciais com 4 Agentes 🚀")

# --- Obter o Tópico do Usuário ---
topico = input("❓ Por favor, digite o TÓPICO sobre o qual você quer criar o laudo pericial: ")

# Inserir lógica do sistema de agentes ################################################
if not topico:
    print("Você não digitou um tópico. Por favor, tente novamente.")
else:
    print(f"Maravilha! Vamos então criar um laudo pericial sobre o tópico: {topico}")

    lancamentos_buscados = agente_buscador(topico, data_de_hoje)
    print("\n--- 📝 Resultado do Agente 1 (Buscador) ---\n")
    display(to_markdown(lancamentos_buscados))
    print("---------------------------------------------------------------------")

    plano_de_laudo = agente_planejador(topico, lancamentos_buscados)
    print("\n--- 📝 Resultado do Agente 2 (Planejador) ---\n")
    display(to_markdown(plano_de_laudo))
    print("---------------------------------------------------------------------")

    rascunho_de_laudo = agente_redator(topico, plano_de_laudo)
    print("\n--- 📝 Resultado do Agente 3 (Redator) ---\n")
    display(to_markdown(rascunho_de_laudo))
    print("---------------------------------------------------------------------")

    laudo_revisado = agente_revisor(topico, rascunho_de_laudo)
    print("\n--- 📝 Resultado do Agente 4 (Revisor) ---\n")
    display(to_markdown(laudo_revisado))
    print("---------------------------------------------------------------------")

